CREATE SEQUENCE T_ROLE_PERMISSION_ID_SEQ INCREMENT BY 1 MINVALUE 1000 NO MAXVALUE START WITH 1000;
CREATE TABLE T_ROLE_PERMISSION
(
    ROLE_PERMISSION_ID BIGINT      NOT NULL DEFAULT NEXTVAL('T_ROLE_PERMISSION_ID_SEQ') PRIMARY KEY,
    ROLE_ID            BIGINT      NOT NULL,
    PERMISSION_ID      BIGINT      NOT NULL,
    CREATE_TIME        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATE_TIME        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);