CREATE SEQUENCE T_USER_ID_SEQ INCREMENT BY 1 MINVALUE 1000 NO MAXVALUE START WITH 1000;
CREATE TABLE T_USER
(
    USER_ID     BIGINT      NOT NULL DEFAULT NEXTVAL('T_USER_ID_SEQ') PRIMARY KEY,
    NAME        VARCHAR(64) NULL,
    MOBILE      VARCHAR(64) NOT NULL,
    PASSWORD    VARCHAR(64) NOT NULL,
    SALT        VARCHAR(64) NOT NULL,
    STATUS      VARCHAR(64) NOT NULL,
    CREATE_TIME TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATE_TIME TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (NAME)
);